from typing import Any

from click.testing import CliRunner

from llm_sbom import __version__
from llm_sbom.cli import main
from llm_sbom.huggingface import HuggingFaceReadmeOptions, render_huggingface_readme
from llm_sbom.schema import SBOMDocument


def test_version_command_prints_package_version() -> None:
    runner = CliRunner()

    result = runner.invoke(main, ["version"])

    assert result.exit_code == 0
    assert result.output.strip() == __version__


def test_scan_empty_directory_table_output() -> None:
    runner = CliRunner()

    with runner.isolated_filesystem():
        result = runner.invoke(main, ["scan", ".", "--format", "table"])

    assert result.exit_code == 0
    assert "No model files found." in result.output


def test_render_hf_readme_infers_curated_metadata() -> None:
    document = _sample_document()

    rendered = render_huggingface_readme(document, HuggingFaceReadmeOptions())

    assert 'title: "LFM2.5-1.2B-Instruct-Q8_0"' in rendered
    assert "tags:" in rendered
    assert '  - "liquid"' in rendered
    assert '  - "gguf"' in rendered
    assert "This README content was generated by `L-BOM`" in rendered
    assert "- **License:** `lfm1.0`" in rendered
    assert "- **Languages:** `en`, `fr`" in rendered
    assert "tokenizer.chat_template" not in rendered


def test_render_hf_readme_honors_overrides() -> None:
    document = _sample_document()

    rendered = render_huggingface_readme(
        document,
        HuggingFaceReadmeOptions(
            title="LocalFusion Demo",
            sdk="static",
            app_file="index.html",
            short_description="Custom summary",
        ),
    )

    assert 'title: "LocalFusion Demo"' in rendered
    assert 'sdk: "static"' in rendered
    assert 'app_file: "index.html"' in rendered
    assert 'short_description: "Custom summary"' in rendered
    assert "# LocalFusion Demo" in rendered


def test_render_hf_readme_includes_warnings() -> None:
    document = _sample_document(warnings=["Quantization may need review."])

    rendered = render_huggingface_readme(document, HuggingFaceReadmeOptions())

    assert "## Warnings" in rendered
    assert "- Quantization may need review." in rendered


def test_scan_hf_readme_rejects_multi_model_directory() -> None:
    runner = CliRunner()

    with runner.isolated_filesystem():
        with open("one.gguf", "wb") as handle:
            handle.write(b"bad")
        with open("two.gguf", "wb") as handle:
            handle.write(b"bad")

        result = runner.invoke(main, ["scan", ".", "--format", "hf-readme"])

    assert result.exit_code != 0
    assert "single model file at a time" in result.output


def _sample_document(**overrides: object) -> SBOMDocument:
    values: dict[str, Any] = {
        "sbom_version": "1.0",
        "generated_at": "2026-03-25T04:07:53.262551+00:00",
        "tool_name": "l-bom",
        "tool_version": "0.1.0",
        "model_path": r"C:\models\LFM2.5-1.2B-Instruct-GGUF\LFM2.5-1.2B-Instruct-Q8_0.gguf",
        "model_filename": "LFM2.5-1.2B-Instruct-Q8_0.gguf",
        "file_size_bytes": 1246253888,
        "sha256": "f6b981dcb86917fa463f78a362320bd5e2dc45445df147287eedb85e5a30d26a",
        "format": "gguf",
        "architecture": "lfm2",
        "parameter_count": 1170340608,
        "quantization": "Q5_1",
        "dtype": None,
        "context_length": 128000,
        "vocab_size": 65536,
        "license": None,
        "base_model": None,
        "training_framework": None,
        "metadata": {
            "general.name": "4cd563d5a96af9e7c738b76cd89a0a200db7608f",
            "general.size_label": "1.2B",
            "general.license": "other",
            "general.license.name": "lfm1.0",
            "general.license.link": "LICENSE",
            "general.tags": ["liquid", "text-generation"],
            "general.languages": ["en", "fr"],
            "tokenizer.chat_template": "huge value that should not leak into the README",
        },
        "warnings": [],
    }
    values.update(overrides)
    return SBOMDocument(**values)
