"""Helpers for exporting Hugging Face-friendly README metadata."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TypeAlias

from .schema import SBOMDocument

FrontMatterValue: TypeAlias = str | int | bool | list[str]
FrontMatter: TypeAlias = dict[str, FrontMatterValue]


@dataclass(frozen=True)
class HuggingFaceReadmeOptions:
    title: str | None = None
    sdk: str | None = None
    app_file: str | None = None
    app_port: int | None = None
    short_description: str | None = None


@dataclass(frozen=True)
class HuggingFaceReadmeDocument:
    front_matter: FrontMatter
    body: str


def build_huggingface_readme(
    document: SBOMDocument, options: HuggingFaceReadmeOptions
) -> HuggingFaceReadmeDocument:

    title = options.title or _derive_title(document)
    short_description = options.short_description or _derive_short_description(document, title)

    front_matter: FrontMatter = {
        "title": title,
        "short_description": short_description,
    }
    if options.sdk:
        front_matter["sdk"] = options.sdk
    if options.app_file:
        front_matter["app_file"] = options.app_file
    if options.app_port is not None:
        front_matter["app_port"] = options.app_port

    models = _extract_models(document)
    if models:
        front_matter["models"] = models

    tags = _extract_tags(document)
    if tags:
        front_matter["tags"] = tags

    body = _render_readme_body(document, title, short_description)
    return HuggingFaceReadmeDocument(front_matter=front_matter, body=body)


def render_huggingface_readme(document: SBOMDocument, options: HuggingFaceReadmeOptions) -> str:

    readme = build_huggingface_readme(document, options)
    return f"{_render_front_matter(readme.front_matter)}\n\n{readme.body}\n"


def _derive_title(document: SBOMDocument) -> str:

    metadata_name = _metadata_string(document.metadata, "general.name")
    if metadata_name and not _looks_like_hash(metadata_name):
        return metadata_name
    return Path(document.model_filename).stem


def _derive_short_description(document: SBOMDocument, title: str) -> str:

    details: list[str] = []
    if document.parameter_count is not None:
        details.append(f"{_format_compact_number(document.parameter_count)} parameters")
    size_label = _metadata_string(document.metadata, "general.size_label")
    if size_label:
        details.append(size_label)
    if document.quantization:
        details.append(document.quantization)
    if document.context_length is not None:
        details.append(f"{_format_compact_number(document.context_length)} context")

    summary = f"{document.format.upper()} model artifact for {title}"
    if details:
        summary = f"{summary} with {', '.join(details)}"
    return summary


def _extract_models(document: SBOMDocument) -> list[str]:

    candidates = [
        document.base_model,
        _metadata_string(document.metadata, "base_model"),
        _metadata_string(document.metadata, "base_model_repo_id"),
        _metadata_string(document.metadata, "source_model"),
    ]

    models: list[str] = []
    for candidate in candidates:
        if candidate is None or "/" not in candidate:
            continue
        if candidate not in models:
            models.append(candidate)
    return models


def _extract_tags(document: SBOMDocument) -> list[str]:

    tags: list[str] = []
    metadata_tags = document.metadata.get("general.tags")
    if isinstance(metadata_tags, list):
        for tag in metadata_tags:
            normalized = _normalize_tag(tag)
            if normalized and normalized not in tags:
                tags.append(normalized)

    for value in (document.format, document.architecture, document.quantization):
        normalized = _normalize_tag(value)
        if normalized and normalized not in tags:
            tags.append(normalized)

    return tags


def _render_readme_body(document: SBOMDocument, title: str, short_description: str) -> str:

    lines = [
        f"# {title}",
        "",
        short_description,
        "",
        "This README content was generated by `L-BOM` from a local model artifact.",
        "",
        "## Artifact details",
        "",
    ]

    _append_bullet(lines, "Filename", f"`{document.model_filename}`")
    _append_bullet(lines, "Path", f"`{document.model_path}`")
    _append_bullet(lines, "Format", _code_or_none(document.format))
    _append_bullet(lines, "File size", _format_file_size(document.file_size_bytes))
    _append_bullet(lines, "SHA256", _code_or_none(document.sha256))
    _append_bullet(lines, "Architecture", _code_or_none(document.architecture))
    _append_bullet(lines, "Parameters", _format_parameter_count(document.parameter_count))
    _append_bullet(lines, "Size label", _code_or_none(_metadata_string(document.metadata, "general.size_label")))
    _append_bullet(lines, "Quantization", _code_or_none(document.quantization))
    _append_bullet(lines, "Dtype", _code_or_none(document.dtype))
    _append_bullet(lines, "Context length", _format_optional_int(document.context_length))
    _append_bullet(lines, "Vocabulary size", _format_optional_int(document.vocab_size))

    metadata_lines: list[str] = []
    license_name = _extract_license_name(document)
    license_link = _metadata_string(document.metadata, "general.license.link")
    _append_bullet(metadata_lines, "License", _code_or_none(license_name))
    _append_bullet(metadata_lines, "License reference", _code_or_none(license_link))
    _append_bullet(metadata_lines, "Base model", _code_or_none(document.base_model))
    _append_bullet(metadata_lines, "Training framework", _code_or_none(document.training_framework))

    languages = _extract_languages(document)
    if languages:
        _append_bullet(metadata_lines, "Languages", ", ".join(f"`{language}`" for language in languages))

    tags = _extract_tags(document)
    if tags:
        _append_bullet(metadata_lines, "Tags", ", ".join(f"`{tag}`" for tag in tags))

    if metadata_lines:
        lines.extend(["", "## Model metadata", ""])
        lines.extend(metadata_lines)

    if document.warnings:
        lines.extend(["", "## Warnings", ""])
        for warning in document.warnings:
            lines.append(f"- {warning}")

    return "\n".join(lines)


def _extract_license_name(document: SBOMDocument) -> str | None:

    return (
        document.license
        or _metadata_string(document.metadata, "general.license.name")
        or _metadata_string(document.metadata, "general.license")
    )


def _extract_languages(document: SBOMDocument) -> list[str]:

    raw_languages = document.metadata.get("general.languages")
    if not isinstance(raw_languages, list):
        return []

    languages: list[str] = []
    for language in raw_languages:
        if not isinstance(language, str):
            continue
        normalized = language.strip()
        if normalized and normalized not in languages:
            languages.append(normalized)
    return languages


def _append_bullet(lines: list[str], label: str, value: str | None) -> None:

    if value is None:
        return
    lines.append(f"- **{label}:** {value}")


def _render_front_matter(front_matter: FrontMatter) -> str:

    lines = ["---"]
    for key, value in front_matter.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {_yaml_scalar(item)}")
            continue
        lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines)


def _yaml_scalar(value: str | int | bool) -> str:

    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def _metadata_string(metadata: dict[str, Any], key: str) -> str | None:

    value = metadata.get(key)
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None


def _normalize_tag(value: str | None) -> str | None:

    if value is None:
        return None
    normalized = value.strip().lower().replace(" ", "-")
    return normalized or None


def _code_or_none(value: str | None) -> str | None:

    if value is None:
        return None
    return f"`{value}`"


def _format_optional_int(value: int | None) -> str | None:

    if value is None:
        return None
    return f"`{value:,}`"


def _format_parameter_count(value: int | None) -> str | None:

    if value is None:
        return None
    return f"`{value:,}` ({_format_compact_number(value)})"


def _format_compact_number(value: int) -> str:

    thresholds = (
        (1_000_000_000, "B"),
        (1_000_000, "M"),
        (1_000, "K"),
    )
    for threshold, suffix in thresholds:
        if value >= threshold:
            return f"{value / threshold:.2f}{suffix}"
    return str(value)


def _format_file_size(size_bytes: int) -> str:

    if size_bytes < 1024:
        return f"`{size_bytes} B`"

    units = ("KiB", "MiB", "GiB", "TiB")
    value = float(size_bytes)
    for unit in units:
        value /= 1024
        if value < 1024 or unit == units[-1]:
            return f"`{value:.2f} {unit}` ({size_bytes:,} bytes)"
    return f"`{size_bytes:,} bytes`"


def _looks_like_hash(value: str) -> bool:

    return bool(re.fullmatch(r"[0-9a-fA-F]{16,}", value))
